class ParallelSentence:
    def __init__(self):
        self.map = {
            'naimbag a bigat': 'good morning',
            'agyamanak': 'thank you',
            'nasayaat, sika': 'fine, and you?',
            'Kaaduen na ti mangan.': 'He will eat much.',
            'Sapaen na ti umay ditoy.': 'He will come here early.',
            'Partakan na ti magna.': 'He will walk fast.',
            'Piduaen na ti mangan.': 'He will eat twice.',
            'Pitloen na nga digusen diay ubing.': 'He will bathe the child three times.',
            'Namindua da nga nangan.': 'They ate twice.',
            'Pinidua da ti nangan.': 'They ate twice.',
            'Agsangit diay ubing.': 'The child will cry.',
            'Diay ubing ti agsangit.': 'It is the child who will cry.',
            'Ubing ti agsangit.': 'It is a child who will cry.',
            'Diay ubing agsangit.': 'The child will cry.',
            'Diay ubing ket agsangit.': 'The child will cry.',
            'Gatangen diay ubing diay mangga.': 'The child will buy the mango.',
            'Gumatang iti mangga diay ubing.': 'The child will buy a mango.',
            'Diay ubing ti gumatang kadeydiay mangga.': 'It is the child who will buy the mango.',
            'Isu ti nakakita ken Marya.': 'It was he who saw Mary.',
            'Isu ti nakakita ken ni Marya.': 'It was he who saw Mary.',
            'Ti bilin na ket daytoy.': 'This is his request.',
            'Nagtudo ken nagbagyo.': 'It rained and stormed.',
            'Mangan ka no mabisin ka.': 'Eat if you are hungry.',
            'Isu ti saan nga abugado.':'He is the one who is not a lawyer.',
            'Saan nga napintas diay balay mo.': 'Your house is not beautiful.',
            'Saan nga diay balay mo ti napintas.': 'It is not your house which is beautiful.',
            'Saan ka nga napintas.': 'You are not beautiful.',
            'Agdigdigosak.': 'I am taking a bath.',
            'Mayat diay padi nga umay ka ditoy.': 'The priest allows you to come here.',
            'Kayat diay padi ti umay ditoy.': 'The priest wants to come here.',
            'Kayat na ti gumatang ti balay.': 'He wants to buy a house.',
            'Balay ti kayat na nga gatangen.': 'What he wants to buy is a house.',
            'Madi diay balasang nga maturog ka ditoy.': 'The lady does not want you to sleep here.',
            'Madi nga maturog ditoy diay balasang.': 'The lady does not want to sleep here.',
            'Kayat ko daytoy.': 'I like this.',
            'Saan ko nga kayat ti coke.': 'I do not like coke.',
            'Masapul ko ti papel.': 'I need some paper.',
            'Kaykayat ko ti coke ngem pepsi.': 'I prefer coke to pepsi.',
            'Agsakitak sa.': 'I think I am sick.',
            'Agsakit ti ulok.': 'I have headache.',
            'Agsakit ti tiyan ko.': 'I have stomachache.',
            'Maspul ko ti doktor.': 'I need a doctor.',
            'Mangayab ka man ti doktor.': 'Please call a doctor.',
            'Mabannog ak.': 'I am tired.',
        }

    def lookup_parallel(self, ilocano_input):
        return self.map.get(ilocano_input.lower())
